package com.aeternum.systems.titles;

public enum TitleEffect {
    ATTACK_BOOST_5, ATTACK_BOOST_10, ATTACK_BOOST_15, ATTACK_BOOST_20,
    DEFENSE_BOOST_5, DEFENSE_BOOST_10, DEFENSE_PENALTY_10,
    CRIT_BOOST_5, CRIT_BOOST_10, DODGE_BOOST_5,
    SPEED_BOOST_5, SPEED_BOOST_10,
    REGEN_SMALL, REGEN_MEDIUM, REGEN_ON_LOW_HP,
    HOLY_DAMAGE_BONUS, DARK_DAMAGE_BONUS,
    AOE_BOOST_10, BOSS_DAMAGE_BONUS,
    EXECUTE_BONUS, STEALTH_SPEED, FEAR_AURA,
    WATER_BREATHING, WATER_POWER, FALL_NEGATION, FIRE_RESISTANCE,
    VOID_RESISTANCE, LUCK_BOOST,
    XP_BOOST_5, XP_BOOST_10, ALL_STATS_5, ALL_STATS_10, ALL_STATS_15, ALL_STATS_20,
    TRADE_DISCOUNT_5, TRADE_DISCOUNT_10, TRADE_DISCOUNT_15,
    TAX_REDUCTION, AURUM_AURA, KARMA_BOOST_PASSIVE,
    COMMAND_AURA, CHARISMA_BOOST, CRAFT_QUALITY_BOOST,
    POTION_POTENCY, ENCHANT_POWER, TAME_DISCOUNT,
    LEGEND_AURA, TRANSCEND_AURA
}
